# Generated by Django 4.1.1 on 2022-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reg_category_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
